disabled_rules:
  # SwiftUI makes it hard to use this rule
  - multiple_closures_with_trailing_closure
  # TODO are usefull
  - todo
  # It is sometimes usefull to have nested types
  - nesting

identifier_name:
  excluded: # excluded via string array
  - id
